annotations:
  io.giantswarm.application.team: team-cabbage
  io.giantswarm.ui.logo: https://s.giantswarm.io/app-icons/ingress-nginx/2/logo_dark.svg
  io.giantswarm.application.audience: "all"
  io.giantswarm.application.managed: "true"
apiVersion: v2
appVersion: 1.14.2
description: Ingress controller for Kubernetes using NGINX as a reverse proxy and load balancer
home: https://github.com/giantswarm/ingress-nginx-app
icon: https://s.giantswarm.io/app-icons/ingress-nginx/2/icon_dark.svg
keywords:
  - ingress
  - nginx
kubeVersion: '>=1.21.0-0'
maintainers:
  - name: cpanato
  - name: Gacko
  - name: strongjz
  - name: tao12345666333
name: ingress-nginx
sources:
  - https://github.com/kubernetes/ingress-nginx
version: 4.2.2
