name: "Validate sync diffs"

on: [pull_request]

jobs:
  check:
    name: "Check sync.sh was called"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Download vendir
        uses: giantswarm/install-binary-action@v3
        with:
          binary: "vendir"
          version: "0.44.0"
          download_url: "https://github.com/carvel-dev/vendir/releases/download/v${version}/vendir-linux-amd64"
          smoke_test: "${binary} --version"

      - name: Download helm-docs
        uses: giantswarm/install-binary-action@v3
        with:
          binary: "helm-docs"
          version: "1.14.2"
          download_url: "https://github.com/norwoodj/helm-docs/releases/download/v${version}/helm-docs_${version}_Linux_x86_64.tar.gz"
          tarball_binary_path: "helm-docs"
          smoke_test: "${binary} --version"

      - name: Run sync.sh
        run: |
          ./sync/sync.sh

      - name: Check there is no diff
        run: |
          git diff --exit-code
